"""The `well` table -- one row per submitted well record: a fixed set of
structural/audit columns plus the ~62 dictionary-driven columns generated by
`db/codegen.py` from MASTER.xlsx's Well-scope parameters (see
db/generated/well_columns.py, never hand-edited).
"""
from __future__ import annotations

from sqlalchemy import Column, DateTime, ForeignKey, Integer, Table, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship

from db.base import Base
from db.generated.well_columns import WELL_COLUMNS

well_table = Table(
    "well",
    Base.metadata,
    Column("id", Integer, primary_key=True),
    Column("organization_id", Integer, ForeignKey("organizations.id"), nullable=False, index=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()),
    # The client's own `generated_at` timestamp from the export JSON, distinct
    # from `created_at` (when the row was written to this DB).
    Column("submitted_at", DateTime(timezone=True), nullable=True),
    # Full original ingest payload, for audit / recovery if a codegen or
    # mapping bug ever loses fidelity in the normalized columns.
    Column("raw_payload", JSONB, nullable=True),
    *WELL_COLUMNS,
)


class Well(Base):
    __table__ = well_table

    organization = relationship("Organization")
    completion_intervals = relationship(
        "CompletionInterval",
        back_populates="well",
        cascade="all, delete-orphan",
        order_by="CompletionInterval.ordinal",
    )
